version: '3'
services:
    app:
        build:
            args:
                NODE_ENV: production
            context: .
        env_file: .env.production
        ports:
            - 127.0.0.1:${PORT:-8204}:${PORT:-8204}
