version: '3'
services:
    app:
        env_file:
            - .env
        build:
            context: .
        ports:
            - ${PORT:-8204}:${PORT:-8204}
        environment:
            NODE_ENV: production
